# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentsdata',
            name='apmt_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
